### ISSUE TITLE
JNIAST usage examples for WCS converison

### ISSUE THREAD

**Issue by PragyaM** [Starlink/starjava#2]
Hi there,

I am trying to convert coordinates between two WCS using JNIAST. I have read some of the documentation for AST (the C version) to understand how it is done, but am finding it tricky to do the same with JNIAST.
I have been using the JNIAST test cases for reference but some of the steps used there are not working for me. I already have the FITS Files I need loaded into the program and will not be loading them from a resource that is included in the project directory.

Do you have any examples or advice about using JNIAST as a library for converting between two WCSs?

In case it helps, I have been using nom.tam.fits for general FITS handling in all other parts of my program, so if there is any way to pass nom.tam.fits Fits components into JNIAST, that would be ideal.

Thanks for making this library available - it was the only suitable Java option I could find for WCS conversion. I would be ever so grateful for any information you can provide.

**Comment by dsberry** [comment]
Hi - I'm not exactly sure what you want to do, but as a very simple example,  here's code that reads a pair of 2-dimensional FrameSets from two text files (each holding a set of FITS-WCS headers), and then gets a FrameSet that converts positions from pixel coordinates in one header to pixel coordinates in the other header, assuming the headers should be aligned on the sky (i.e. aligned in celestial coordinates). It then uses the FrameSet to transform some pixel coordinates. Hope this helps.

```
import uk.ac.starlink.ast.*;
import java.util.Arrays;

public class Tester {
   public static void main( String[] args ) {

/* Read in a FrameSet from text file "header1.head" holding FITS-WCS Headers. */
      FitsChan fc1 = new FitsChan( );
      fc1.set( "SourceFile=header1.head" );
      fc1.clear("Card");
      FrameSet fs1 = (FrameSet) fc1.read();

/* Read in a FrameSet from text file "header2.head" holding FITS-WCS Headers. */
      FitsChan fc2 = new FitsChan( );
      fc2.set( "SourceFile=header2.head" );
      fc2.clear("Card");
      FrameSet fs2 = (FrameSet) fc2.read();

/* We want to align the two FrameSets in world coordinats, so invert them
   before using the Convert method. */
      fs1.invert();
      fs2.invert();
      FrameSet fs3 = fs1.convert( fs2, "SKY" );

/* The "fs3" FrameSet describes the transformation from pixel coords in
   "header1.head" to pixel coords in "header2.head". Use it to transform
   some pixel coordinates. */
      double[] xin = new double[] { 10, 20, 40 };
      double[] yin = new double[] { 2, 4, 8 };
      double[][] result = fs3.tran2( 3, xin, yin, true );
      System.out.println(Arrays.deepToString(result));

/* Transform them back again. */
      double[][] result2 = fs3.tran2( 3, result[0], result[1], false );
      System.out.println(Arrays.deepToString(result2));

   }
}
```

**Comment by PragyaM** [comment]
Thanks a lot - that is exactly what I needed.
