### ISSUE TITLE
topcat save jdbc fails if column varchar(0) ie is empty

### ISSUE THREAD

**Issue by bourgesl** [Starlink/starjava#55]
In topcat jdbc save, stats are computed to determine the max length of String columns.

When the column is entirely empty, topcat emits the DDL command:
Create table ... (... my_col_name VARCHAR(0) ...)

Postgres returns an sql failure:
my_col_name size must be > 1

Please ignore empty cols in sql queries would be great. Ideally a prompt dialog could indicate skipped columns.

**Comment by mbtaylor** [comment]
Hi @bourgesl.  I think the less surprising behaviour would be to ensure a minimum length (in the case of an empty string column) of `VARCHAR(1)`, which presumably postgres would be OK with, rather than skipping the column for output.  Do you agree?

**Comment by bourgesl** [comment]
It is easier and a good idea but it wastes space in postgres...
I agree it is user's fault if the table has empty columns.

However, votable params could be considered as fixed-value columns too. 

Should such constant values be stored as table columns too like empty cols ?

**Comment by mbtaylor** [comment]
I'll go with inefficient over surprising, and do what I proposed.  Can you try the version at ftp://andromeda.star.bris.ac.uk/pub/star/topcat/pre/topcat-full_varchar.jar and tell me if it behaves better?

Regarding VOTable PARAMs, and table parameters in general: I'm not going to write them as table columns in output to JDBC or other formats, for reasons including: there may be many of them, they may have large values, they may not be very interesting.  There are ways for the user to add new columns to the table with the (constant) values of such parameters if they want to do that.

**Comment by bourgesl** [comment]
I tried topcat-full_varchar.jar and it passes: import is in progress...

Thank you,
Happy New Year 21 & best wishes,
Laurent

**Comment by mbtaylor** [comment]
Great, thanks Laurent.  Fixed at a675a0833.
