### ISSUE TITLE
FitsTableBuilder does not release ArrayDataInput Object.

### ISSUE THREAD

**Issue by vforchi** [Starlink/starjava#6]
The method makeStarTable does not release the ArrayDataInput if the table has been created:
```
finally {
            if ( strm != null && table == null ) {
                strm.close();
            }
}
```

I don't know if this is by design or not, but this does not release the file descriptor. As a consequence, a program I wrote runs out of file descriptors after a while.

**Comment by mbtaylor** [comment]
Oops, you're right.  It was by design, but is a relic of some nasty code I removed a couple of years back and so the `table==null` condition can be removed.  I have fixed this at  262e27024b60.
Thanks @vforchi  very much for tracking it down.
