### ISSUE TITLE
taplint/votlint UNKNOWN_UNIT warnings are reported without the first character of unit string

### ISSUE THREAD

**Issue by esabol** [Starlink/starjava#61]
taplint and votlint both report warnings like the following:
```
WARNING (l.19, c.94): Bad VOUnit "degree" (UNKNOWN_UNIT): Unknown unit "egree"
WARNING (l.28, c.79): Bad VOUnit "mjd" (UNKNOWN_UNIT): Unknown unit "jd"
```
It seems like a bug that it says "egree" and "jd" instead of "degree" and "mjd" in the warning? It gets the units correct initially where it says "Bad VOUnit ...", but then it removes the first character where it says "Unknown unit ..."

**Comment by mbtaylor** [comment]
It has interpreted these as a deci-egree and a milli-jd respectively, where the "egree" and "jd" are unrecognised, but syntactically permissible units.  I agree this is a bit unintuitive.  These messages are generated by a third-party library [Unity](https://code.nxg.name/nxg/unity), and in fact there are some changes in progress to improve these messages, but for one reason and another the updates are not ready to apply yet.  So things might look better in future releases.  But in the mean time it's probably best to take the text of these unit warnings as a hint that there's something non-compliant somewhere.

**Comment by esabol** [comment]
Ah, OK. Thanks for the explanation.
