### ISSUE TITLE
[util] test failure in testString

### ISSUE THREAD

**Issue by olebole** [Starlink/starjava#68]
I just started to update the Debian packages to topcat-4.9.1 & co. (was delayed since Github removed the SVN access which I used to get individual starjava packages). In the "util" package, my build fails in the unit test step with
```
    [junit] Testcase: testString took 0.007 sec
    [junit] 	FAILED
    [junit] expected:<$[?]?> but was:<$[]?>
    [junit] junit.framework.ComparisonFailure: expected:<$[?]?> but was:<$[]?>
    [junit] 	at junit.framework.Assert.assertEquals(Assert.java:81)
    [junit] 	at junit.framework.Assert.assertEquals(Assert.java:87)
    [junit] 	at uk.ac.starlink.util.PrimitiveListTest.testString(PrimitiveListTest.java:150)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    [junit] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    [junit] 	at junit.framework.TestCase.runTest(TestCase.java:164)
    [junit] 	at junit.framework.TestCase.runBare(TestCase.java:130)
    [junit] 	at junit.framework.TestResult$1.protect(TestResult.java:106)
    [junit] 	at junit.framework.TestResult.runProtected(TestResult.java:124)
    [junit] 	at junit.framework.TestResult.run(TestResult.java:109)
    [junit] 	at junit.framework.TestCase.run(TestCase.java:120)
    [junit] 	at junit.framework.TestSuite.runTest(TestSuite.java:230)
    [junit] 	at junit.framework.TestSuite.run(TestSuite.java:225)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:535)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:1197)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:1042)
    [junit] 

BUILD FAILED
/build/starjava-util-1.0+2024.01.29/build.xml:932: Test uk.ac.starlink.util.PrimitiveListTest failed
```

which I do not fully understand. The test code here is https://github.com/Starlink/starjava/blob/a4447132ba0f5041f6cf95632575e39ae735e8fd/util/src/testcases/uk/ac/starlink/util/PrimitiveListTest.java#L146-L150

The used SDK is openjdk-17 (17.0.11) on Debian unstable.

**Comment by mbtaylor** [comment]
Hi @olebole, I don't understand it either.  I can only imagine it's some kind of locale-related thing, though I really don't see how.  I can't reproduce it using Oracle Java 17.0.6 with e.g. `Locale.setDefault(Locale.GERMANY)`.

I've decorated the offending test method with some added some diagnostics to stdout.  Could you try checking out branch `issue68` from https://github.com/mbtaylor/starjava/ and telling me what the output looks like?  What I see is this:
```
    [junit] ------------- Standard Output ---------------
    [junit] Locale: en_GB
    [junit] req: 
    [junit]     chr 0: 0x24     0x24    >$<
    [junit]     chr 1: 0xa3     0xa3    >£<
    [junit]     getBytes:       [36, -62, -93]
    [junit]     getBytes(UTF8)  [36, -62, -93]
    [junit] got: 
    [junit]     chr 0: 0x24     0x24    >$<
    [junit]     chr 1: 0xa3     0xa3    >£<
    [junit]     getBytes:       [36, -62, -93]
    [junit]     getBytes(UTF8)  [36, -62, -93]
    [junit] ------------- ---------------- ---------------
```
The `getBytes:` lines might differ, but the other three lines should be the same for `req` and `got`.

**Comment by olebole** [comment]
Sorry that I didn't answer quickly.
Here is my result (after expülicitly setting the default locale to `Locale.UK` to avoid locale problems):
```
   [junit] Locale: en_GB
    [junit] req: 
    [junit] 	chr 0: 0x24	0x24	>$<	
    [junit] 	chr 1: 0xc2	0xc2	>?<	
    [junit] 	chr 2: 0xa3	0xa3	>?<	
    [junit] 	getBytes:	[36, -61, -126, -62, -93]
    [junit] 	getBytes(UTF8)	[36, -61, -126, -62, -93]
    [junit] got: 
    [junit] 	chr 0: 0x24	0x24	>$<	
    [junit] 	chr 1: 0xa3	0xa3	>?<	
    [junit] 	getBytes:	[36, -62, -93]
    [junit] 	getBytes(UTF8)	[36, -62, -93]
```

**Comment by mbtaylor** [comment]
Maybe this is to do with the locale at compile time not test time?  It seems like the string literal in the source code is being interpreted differently in your environment than mine, which I didn't expect to happen.  I've made an update to fix the Unicode code points of the string being tested against, can you update from the `issue68` branch and try again?  Hopefully it will pass this time.

**Comment by olebole** [comment]
The failure still remains:
```
    [junit] Locale: en_US
    [junit] req: 
    [junit] 	chr 0: 0x24	0x24	>$<	
    [junit] 	chr 1: 0xc2	0xc2	>?<	
    [junit] 	chr 2: 0xa3	0xa3	>?<	
    [junit] 	getBytes:	[36, -61, -126, -62, -93]
    [junit] 	getBytes(UTF8)	[36, -61, -126, -62, -93]
    [junit] got: 
    [junit] 	chr 0: 0x24	0x24	>$<	
    [junit] 	chr 1: 0xa3	0xa3	>?<	
    [junit] 	getBytes:	[36, -62, -93]
    [junit] 	getBytes(UTF8)	[36, -62, -93]
```
I played around a bit with setting **LANG** and **LC_ALL** to `C` or `C.utf8`, but this doesn't help. It only changes the display within `> <`.

**Comment by mbtaylor** [comment]
I am quite mystified by this, I don't understand how the req string can have length()=3 since the two characters it contains are from the BMP.  I can't reproduce it using OpenJDK 17.0.12.

But I've had another go at constructing the req string using a 2-element char array.  Surely this time the string will have a length()=2??  Please could you try building and running the test again from the [head of the issue68 branch](https://github.com/mbtaylor/starjava/commit/d45b597be).

**Comment by olebole** [comment]
OOps, that was my mistake: In the second round, I accidently applied only the first commit again. Replacing `"$£"` with `"\u0024\u00a3"` did the trick. Sorry.

**Comment by mbtaylor** [comment]
OK that's a relief.  I've backed out of the verbose diagnostics, and just included that change of the string content.  There's a new commit on issue68, can you check it works just to be sure?  If so I'll go ahead and apply it on the master branch.

**Comment by olebole** [comment]
Yes I can confirm it works well. Thank you for the help, and sorry for my mistake!

**Comment by mbtaylor** [comment]
No problem, thanks for reporting and testing this.  I have applied the change to the master branch at 6f782af2d9
