### ISSUE TITLE
How do I build stil.jar?

### ISSUE THREAD

**Issue by vforchi** [Starlink/starjava#8]
Hi,

Is there a way to build the file `stil.jar` (the one available from [here](http://www.star.bris.ac.uk/~mbt/stil/stil.jar)) with ant?

Cheers,
Vincenzo

**Comment by mbtaylor** [comment]
No.  Currently the package release machinery is held outside of the git repository.  The makefile target that I use to build the monolithic jar file looks like this:
```
stil.jar stil_jars.zip:
        java -classpath $(STARJAVA_LIB)/util/util.jar \
                        uk.ac.starlink.util.SuperJar \
            $(STARJAVA_LIB)/table/table.jar \
            $(STARJAVA_LIB)/fits/fits.jar \
            $(STARJAVA_LIB)/votable/votable.jar \
            $(STARJAVA_LIB)/cdf/cdf.jar \
            $(STARJAVA_LIB)/gbin/gbin.jar \
            $(STARJAVA_LIB)/connect/connect.jar \
            $(STARJAVA_LIB)/mirage/mirage.jar \
            -xjar junit.jar \
            -xjar hdx.jar \
            -xjar ndx.har \
            -xjar jniast.jar \
            -xjar array.jar \
            -oj stil.jar \
            -oz stil_jars.zip
```
SuperJar is fairly straightforward, but there's help in [the javadocs](http://andromeda.star.bris.ac.uk/starjavadocs/uk/ac/starlink/util/SuperJar.html#main(java.lang.String[])) or with `-h`.
